=== MTen/raml_compiler/js/lib/CO_2.0/item.json
{
    "type": "object",
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "itemID": {
            "type": "string"
        },
        "brandID": {
            "type": "string",
            "description": "The item's parent brand."
        },
        "brandName": {
            "type": "string",
            "description": "The name of the item's parent brand."
        },
        "inventoryCount": {
            "type": "integer",
            "description": "The number of items currently in stock. Specify 0 for out of stock or unavailable items and -1 for unknown."
        },
        "name": {
            "type": "string",
            "description": "A name for the item displayable to the user."
        },
        "popularityRating": {
            "type": "number",
            "description": "An arbitrary float representing how popular this item is. Items with greater popularityRatings will sort to the top by default."
        },
        "price": {
            "$ref": "price.json"
        },
        "package": {
            "$ref": "package.json"
        }
    },
    "required": [
        "itemID",
        "brandID",
        "name",
        "brandName"
    ]
}

=== MTen/raml_compiler/js/AR_2.5Copy/x-regulars.json
[
  {
    "itemID": "55345",
    "name": "1/2 Barrel",
    "inventoryCount": 1,
    "popularityRating": 100,
    "brandID": "BDLLM",
    "brandName": "Bud Light Lime",
    "price": {
      "priceID": "1",
      "unitPrice": 83
    },
    "package": {
      "packageID": "1",
      "name": "1/2 Barrel",
      "imageURL": "keg.png",
      "itemCount": 1,
      "itemSize": 1984,
      "containerCount": 1,
      "unitOfMeasurement": "OZ",
      "containerName": "Keg"
    }
  },
  {
    "itemID": "40130",
    "name": "4 Ct 6 Pk 12 Oz Bottles",
    "inventoryCount": 1,
    "popularityRating": 86,
    "brandID": "BDLLM",
    "brandName": "Bud Light Lime",
    "price": {
      "priceID": "2",
      "unitPrice": 23.9
    },
    "package": {
      "packageID": "2",
      "name": "4 Six Packs, 12 OZ Bottles",
      "imageURL": "bottle.png",
      "itemCount": 6,
      "itemSize": 12,
      "containerCount": 4,
      "unitOfMeasurement": "OZ",
      "containerName": "Bottle"
    }
  }
]
