=== MTen/raml_compiler/js/lib/Master/invoice.json
{
  "type": "object",
  "$schema": "http://json-schema.org/schema",
  "description": "A bill issued to the account",
  "properties": {
    "invoiceID": {
      "type": "string"
    },
    "physicalInvoiceID": {
      "description": "The id found on the physical invoice issued to the account.",
      "type": "string"
    },
    "date": {
      "type": "string",
      "description": "The date of the invoice. Preferred format: yyyy-MM-dd HH:mm:ss-Z."
    },
    "cost": {
      "type": "number",
      "description": "The cost of the invoice."
    },
    "taxAmount": {
      "type": "number",
      "description": "The total tax charged to the order."
    },
    "discountAmount": {
      "type": "number",
      "description": "The total value of the discounts applied to the order."
    },
    "invoiceItems": {
      "$ref": "orderItem.json",
      "description": "The items charged to this invoice."
    },
    "orders": {
      "$ref": "order.json",
      "description": "The orders associated with this invoice. Note: this should only be returned for invoice detail requests, and never in conjunction with invoiceItems."
    }
  },
  "required": [
    "invoiceID",
    "date",
    "cost",
    "invoiceItems"
  ]
}

=== MTen/raml_compiler/js/lib/CO_2.0/x-invoices.json
[
    {
        "invoiceID": "1",
        "physicalInvoiceID": "2",
        "date": "2014-10-11 00:00:00",
        "cost": 290.45,
        "invoiceItems": [
            {
                "orderItemID": "KTKC61",
                "cost": 28.12,
                "itemCount": 1,
                "item": {
                    "brandID": "12642",
                    "brandName": "BECKS SP LIGHT",
                    "itemID": "KTKC6",
                    "name": "BCKLT 4/6/12 LN USP3",
                    "price": {
                        "priceID": "2790",
                        "unitPrice": 26.92
                    }
                }
            }
        ]
    }
]
