=== MTen/raml_compiler/js/lib/Master/merchandise.json
{
  "type": "object",
  "$schema": "http://json-schema.org/schema",
  "description": "A non-beverage product that may be purchased. For instance, an umbrella.",
  "properties": {
    "merchandiseID": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "shippingInfo": {
      "type": "string"
    },
    "imageURL": {
      "type": "string"
    },
    "merchandiseTypeID": {
      "type": "string"
    },
    "family": {
      "type": "string",
      "description": "The brand family the merchandise is associated with."
    },
    "romanceCopy": {
      "type": "string"
    },
    "price": {
      "$ref": "price.json"
    }
  },
  "required": [
    "merchandiseID",
    "name"
  ]
}

=== MTen/raml_compiler/js/AR_2.5Copy/x-merchandise.json
[
  {
    "merchandiseID": "175937",
    "name": "BDL 10ox HW Trans 2500/ca DS",
    "description": "Heavyweight translucent cup. Case of 2500.",
    "shippingInfo": "Ships directly from the vendor via truck within 2-3 business days.",
    "merchandiseTypeID": "1",
    "family": "Budweiser",
    "romanceCopy": "",
    "imageURL": "175937.png",
    "price": {
      "priceID": "2",
      "points": 1000
    }
  }
]
