=== MTen/raml_compiler/js/lib/Master/truck.json
{
    "type": "object",
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "cost": {
            "type": "number",
            "description": "The current cost of the items in the truck."
        },
        "pointsEarned": {
            "type": "number",
            "description": "The number of points this order will earn."
        },
        "orderItems": {
            "type": "array",
            "items": {
                "$ref": "orderItem.json"
            }
        },
        "giftItems": {
            "type": "array",
            "items": {
                "$ref": "orderItem.json"
            }
        }
    }
}

=== MTen/raml_compiler/js/lib/Master/x-truck.json
{
  "cost": 490.72,
  "pointsEarned": 24.54,
  "orderItems": [
    {
      "item": {
        "brandID": "12642",
        "brandName": "BECKS SP LIGHT",
        "itemID": "KTKC6",
        "name": "BCKLT 4/6/12 LN USP3",
        "price": {
          "priceID": "2790",
          "unitPrice": 26.92
        }
      },
      "itemCount": 1
    },
    {
      "item": {
        "brandID": "12642",
        "brandName": "BECKS SP LIGHT",
        "itemID": "KTKC9",
        "name": "BCKLT 5/6/12 LN USP3",
        "price": {
          "priceID": "2791",
          "unitPrice": 30.92
        }
      },
      "itemCount": 15
    }
  ],
  "giftItems": [
    {
      "giftID": "40130",
      "unitPoints": 300,
      "item": {
        "itemID": "55345",
        "inventoryCount": 1,
        "name": "1/2 Barrel",
        "price": {
          "priceID": "1",
          "unitPrice": 83
        },
        "package": {
          "packageID": "1",
          "name": "1/2 Barrel",
          "itemCount": 1,
          "itemSize": 1984,
          "unitCount": 1,
          "unitOfMeasurement": "OZ",
          "containerName": "Keg"
        }
      }
    }
  ]
}
