=== MTen/raml_compiler/js/lib/Master/user.json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "description": "A user representing the interests of an account.",
  "properties": {
    "userID": {
      "type": "string",
      "description": "An email the user uses to log in with or another unique identifier."
    },
    "clientGrade": {
      "type": "string",
      "description": "A client grade potentially displayable to the user."
    },
    "email": {
      "type": "string",
      "description": "The user's email address."
    },
    "name": {
      "type": "string",
      "description": "The user's name."
    },
    "phone": {
      "type": "string",
      "description": "The user's phone number."
    },
    "points": {
      "type": "number",
      "description": "The number of points that the user has earned."
    },
    "accounts": {
      "type": "array",
      "items": {
        "$ref": "account.json"
      }
    },
    "notifications": {
      "type": "array",
      "items": {
        "$ref": "notification.json"
      }
    }
  },
  "required": [
    "userID",
    "name",
    "email",
    "accounts"
  ]
}

=== MTen/raml_compiler/js/AR_2.5Copy/x-user.json
{
  "userID": "FUZZ-158",
  "clientGrade": "S+",
  "email": "noah@fuzzproductions.com",
  "name": "Noah Blake",
  "phone": "212-646-8000",
  "points": 2000,
  "accounts": [
    {
      "custID": "N502",
      "wholesalerID": "43100",
      "route": "AC006",
      "distributionChannel": "01",
      "division": "00",
      "name": "Book Cellar",
      "isAdmin": true,
      "totalCredit": 3000,
      "creditBalance": 205.55,
      "creditExpiration": "2020-05-11 00:00:00",
      "paymentMethods": [
        "CASH",
        "CREDIT",
        "UNION_PAY"
      ],
      "invoiceTypes": [
        {
          "invoiceTypeID": "BE",
          "description": "All Beer"
        },
        {
          "invoiceTypeID": "NB",
          "description": "3% Beer"
        }
      ],
      "deliveryAddresses": [
        {
          "addressID": "1",
          "addressLineOne": "3215 Lind Ave SW",
          "addressLineTwo": "",
          "city": "Renton",
          "state": "WA",
          "zipCode": "98057",
          "contactName": "RJ Stidd",
          "contactNumber": "013335558888"
        }
      ],
      "orderDeadlines": [
        {
          "day": 0,
          "time": "13:30:00"
        },
        {
          "day": 1,
          "time": "16:00:00"
        },
        {
          "day": 2,
          "time": "16:00:00"
        },
        {
          "day": 3,
          "time": "16:30:00"
        },
        {
          "day": 4,
          "time": "16:00:00"
        },
        {
          "day": 5,
          "time": "16:00:00"
        },
        {
          "day": 6,
          "time": "13:00:00"
        }
      ],
      "representatives": [
        {
          "representativeID": "23",
          "name": "RJ",
          "email": "rj@fuzzproductions.com",
          "phone": "212-646-9000"
        }
      ],
      "notifications": [
        {
          "notificationID": "1",
          "description": "Alert me when my order is on its way.",
          "isEnabled": false,
          "day": -1
        }
      ]
    }
  ]
}
