=== MTen/raml_compiler/js/AR_2.5C/notification.json
{
  "type": "object",
  "$schema": "http://json-schema.org/schema",
  "properties": {
    "notificationID": {
      "type": "string"
    },
    "description": {
      "type": "string",
      "description": "A displayable description of the notification."
    },
    "isEnabled": {
      "type": "boolean",
      "description": "An indicator of whether the user has enabled this notification or not. By default, true."
    },
    "day": {
      "type": "integer",
      "description": "Day of the week, enumerated. Sunday = 0, Saturday = 6. -1 denotes a notification that has no relationship to a given day."
    }
  },
  "required": [
    "notificationID",
    "description"
  ]
}

=== MTen/raml_compiler/js/test/lib/AR_2.5/x-notifications.json
[
    {
        "notificationID": "1",
        "description": "Alert me when my order is on its way.",
        "isEnabled": true,
        "day": -1
    },
    {
        "notificationID": "2",
        "description": "Alert me when my order is 30 minutes away.",
        "isEnabled": true,
        "day": -1
    },
    {
        "notificationID": "3",
        "description": "Alert me when my order has been delivered.",
        "isEnabled": true,
        "day": -1
    }
]
