=== MTen/raml_compiler/js/test/lib/CO_2.0/account.json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "description": "A user representing the interests of an account.",
  "properties": {
    "custID": {
      "type": "string",
      "description": "The ID of the customer associated with this account."
    },
    "wholesalerID": {
      "type": "string",
      "description": "The ID of the wholesaler responsible for fulfilling the account's orders."
    },
    "name": {
      "type": "string",
      "description": "The account's name."
    },
    "deliveryWindows": {
      "type": "array",
      "description": "The account's delivery windows.",
      "items": {
        "$ref": "deliveryWindow.json"
      }
    },
    "orderDeadlines": {
      "type": "array",
      "description": "The time at which an order must be placed on a given day for it to be processed by the following morning.",
      "items": {
        "day": {
          "type": "integer",
          "description": "Day of the week, enumerated. Sunday = 0, Saturday = 6."
        },
        "time": {
          "type": "string",
          "description": "The time of the order deadline in the format HH:mm:ss"
        }
      }
    },
    "representatives": {
      "type": "array",
      "description": "The account's sales representatives.",
      "items": {
        "$ref": "representative.json"
      }
    },
    "administrators": {
      "type": "array",
      "description": "The administrators of this account. Note: these users do not appear in the users relationship.",
      "items": {
        "$ref": "user.json"
      }
    },
    "users": {
      "type": "array",
      "description": "The users associated with this account. Note: administrators do not appear in this array.",
      "items": {
        "$ref": "user.json"
      }
    }
  },
  "required": [
    "wholesalerID",
    "custID",
    "name",
    "representatives"
  ]
}

=== MTen/raml_compiler/js/test/lib/CO_2.0/x-account.json
{
  "custID": "N5509",
  "wholesalerID": "857309",
  "name": "Jen's Cantina",
  "deliveryWindows": [
    {
      "deliveryWindowID": "1",
      "startDate": "2014-10-10 20:00:00",
      "endDate": "2014-10-11 00:00:00"
    }
  ],
  "orderDeadlines": [
    {
      "day": 0,
      "time": "13:30:00"
    },
    {
      "day": 1,
      "time": "16:00:00"
    },
    {
      "day": 2,
      "time": "16:00:00"
    },
    {
      "day": 3,
      "time": "16:30:00"
    },
    {
      "day": 4,
      "time": "16:00:00"
    },
    {
      "day": 5,
      "time": "16:00:00"
    },
    {
      "day": 6,
      "time": "13:00:00"
    }
  ],
  "representatives": [
    {
      "representativeID": "23",
      "name": "RJ",
      "email": "rj@fuzzproductions.com",
      "phone": "212-646-9000"
    }
  ],
  "administrators": [
    {
      "userID": "FUZZ-158",
      "email": "noah@fuzzproductions.com",
      "name": "Noah Blake",
      "phone": "212-646-8000"
    }
  ],
  "users": [
    {
      "userID": "FUZZ-159",
      "email": "rj@fuzzproductions.com",
      "name": "RJStidd",
      "phone": "212-646-8000"
    }
  ]
}
