=== MTen/raml_compiler/test/lib/CO_2.0/order.json
{
  "type": "object",
  "$schema": "http://json-schema.org/schema",
  "properties": {
    "orderID": {
      "type": "string"
    },
    "placementDate": {
      "type": "string",
      "description": "The date the order was placed. Preferred format: yyyy-MM-dd HH:mm:ss."
    },
    "isFavorite": {
      "type": "boolean",
      "description": "Indicates if the user has favorited this order or not."
    },
    "name": {
      "type": "string",
      "description": "A name the user has assigned to this order."
    },
    "note": {
      "type": "string",
      "description": "A note the user has added to this order."
    },
    "pricing": {
      "$ref": "pricing.json",
      "description": "An encapsulation of the pricing details associated with this order."
    }
  },
  "required": [
    "orderID"
  ]
}

=== MTen/raml_compiler/test/lib/badDirectory/x-orders.json
[
  {
    "orderID": "1",
    "placementDate": "2014-10-11 00:00:00",
    "note": "Use the side door please",
    "isFavorite": false,
    "name": "Thursday order",
    "pricing": {
      "pricingID": "1",
      "cost": 258.96,
      "taxAmount": 21.3,
      "discountAmount": 32.5,
      "discounts": [
        {
          "discountID": "1",
          "discountAmount": 32.5
        }
      ],
      "orderItems": [
        {
          "orderItemID": "KTKC61",
          "cost": 28.12,
          "itemCount": 1,
          "item": {
            "brandID": "12642",
            "brandName": "BECKS SP LIGHT",
            "itemID": "KTKC6",
            "name": "BCKLT 4/6/12 LN USP3",
            "price": {
              "priceID": "2790",
              "unitPrice": 26.92
            }
          }
        }
      ]
    }
  }
]
