=== MTen/raml_compiler/js/test/lib/badDirectory/item.json
{
  "type": "object",
  "$schema": "http://json-schema.org/schema",
  "properties": {
    "itemID": {
      "type": "string"
    },
    "brandID": {
      "type": "string",
      "description": "The item's parent brand."
    },
    "brandName": {
      "type": "string",
      "description": "The name of the item's parent brand."
    },
    "name": {
      "type": "string",
      "description": "A name for the item displayable to the user."
    },
    "price": {
      "$ref": "price.json"
    },
    "package": {
      "$ref": "package.json"
    }
  },
  "required": [
    "itemID",
    "brandID",
    "name",
    "brandName"
  ]
}

=== MTen/raml_compiler/test/lib/badDirectory/x-items.json
[
  {
    "itemID": "55345",
    "brandID": "BDLLM",
    "brandName": "Kegco",
    "name": "1/2 Barrel",
    "price": {
      "priceID": "1",
      "unitPrice": 83
    },
    "package": {
      "packageID": "1",
      "name": "1/2 Barrel",
      "imageURL": "keg.png",
      "itemCount": 1,
      "itemSize": 1984,
      "returnable": true,
      "unitCount": 1,
      "unitOfMeasurement": "OZ",
      "containerName": "Keg"
    }
  }
]
