=== MTen/raml_compiler/test/lib/badDirectory/pricing.json
{
  "type": "object",
  "$schema": "http://json-schema.org/schema",
  "properties": {
    "pricingID": {
      "type": "string"
    },
    "cost": {
      "type": "number",
      "description": "The final cost of the order after taxes, charges, and discounts have been applied."
    },
    "taxAmount": {
      "type": "number",
      "description": "The total tax charged to the order."
    },
    "discountAmount": {
      "type": "number",
      "description": "The total value of the discounts applied to the order."
    },
    "discounts": {
      "type": "array",
      "items": {
        "$ref": "discount.json"
      }
    },
    "orderItems": {
      "type": "array",
      "items": {
        "$ref": "orderItem.json"
      }
    }
  },
  "required": [
    "pricingID",
    "cost",
    "orderItems"
  ]
}

=== MTen/raml_compiler/js/test/lib/CO_2.0/x-pricing.json
{
  "pricingID": "1",
  "cost": 258.96,
  "taxAmount": 21.3,
  "discountAmount": 32.5,
  "discounts": [
    {
      "discountID": "1",
      "discountAmount": 32.5
    }
  ],
  "orderItems": [
    {
      "orderItemID": "1",
      "cost": 270.16,
      "invoiceID": "1",
      "itemID": "55345",
      "itemCount": 10
    }
  ]
}
