=== MTen/raml_compiler/test/lib/AR_2.5/orderAnalysis.json
{
    "type": "object",
    "$schema": "http://json-schema.org/schema",
    "properties": {
        "orderAnalysisID": {
            "type": "string",
            "description": "Preferred format: yyyy-MM-dd HH:mm:ss."
        },
        "startDate": {
            "type": "string",
            "description": "Preferred format: yyyy-MM-dd HH:mm:ss."
        },
        "endDate": {
            "type": "string"
        },
        "itemCount": {
            "type": "integer",
            "description": "The final cost of the order after taxes, charges, and discounts have been applied"
        },
        "cost": {
            "type": "number",
            "description": "The total tax charged to the order."
        },
        "analysisOfPreviousYear": {
            "$ref": "orderAnalysis.json"
        },
        "orderItems": {
            "type": "array",
            "items": {
                "$ref": "orderItem.json"
            }
        }
    },
    "required": [
        "orderAnalysisID",
        "startDate",
        "endDate",
        "itemCount",
        "cost"
    ]
}

=== MTen/raml_compiler/js/AR_2.5Copy/x-orderAnalysis.json
{
  "orderAnalysisID": "10",
  "startDate": "2014-10-11 00:00:00",
  "endDate": "2014-10-17 00:00:00",
  "itemCount": 25,
  "cost": 1008.5,
  "analysisOfPreviousYear": {
    "orderAnalysisID": "1",
    "startDate": "2013-10-11 00:00:000",
    "endDate": "2014-10-17 00:00:00",
    "itemCount": 18,
    "cost": 800.2
  },
  "orderItems": [
    {
      "orderItemID": "3",
      "isCredit": false,
      "cost": 40.32,
      "orderID": "1",
      "itemID": "33495",
      "itemCount": 25,
      "item": {
        "itemID": "55399",
        "brandID": "BDLLM",
        "name": "1/2 Barrel",
        "popularityRating": 100,
        "price": {
          "priceID": "3",
          "itemID": "55399",
          "unitPrice": 40.32,
          "startDate": "2014-10-11 00:00:00",
          "endDate": "2014-12-11 00:00:00",
          "discount": {},
          "estimate": {}
        },
        "package": {
          "packageID": "1",
          "name": "1/2 Barrel",
          "imageURL": "keg.png",
          "itemCount": 1,
          "itemSize": 1984,
          "containerCount": 1,
          "unitOfMeasurement": "OZ",
          "containerName": "Keg"
        }
      }
    }
  ]
}

=== MTen/raml_compiler/test/lib/AR_2.5/x-orderAnalyses.json
[
    {
        "orderAnalysisID": "10",
        "startDate": "2014-10-11 00:00:00",
        "endDate": "2014-10-17 00:00:00",
        "itemCount": 25,
        "cost": 1008.5,
        "analysisOfPreviousYear": {
            "orderAnalysisID": "1",
            "itemCount": 18,
            "cost": 800.2
        },
        "orderItems": []
    }
]
